export const GET_QUOTES = "GET_QUOTES";
export const QUOTES_ERROR = "QUOTES_ERROR";
export const QUOTES_LOADING = "QUOTES_LOADING";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const GET_NEW_QUOTES = "GET_NEW_QUOTES";
export const GET_FAVOURATES = "GET_FAVOURATES";
export const ADD_FAVOURATES = "ADD_FAVOURATES";
export const REFRESH_QUOTES = "REFRESH_QUOTES";


